[package]
name = "igait-ssh-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssh = { version = "0.10.3", features = ["native-mux"] }
tokio = { version = "1.36.0", features = ["full"] }
